site_name: worker-ng documentation
site_description: worker-ng is intended to easily submit and manage embarrasignly parallel computations for, e.g., parameter exploration
site_author: Geert Jan Bex
nav:
- Introduction and motivation: 'index.md'
- Step by step: 'steps.md'
- Monitoring worker jobs: 'monitoring.md'
- Resuming a worker job: 'resume.md'
- Limiting execution time: 'time_limits.md'
- Multithreaded work items: 'multithreading.md'
- Prologue and epilogue: 'mapreduce.md'
- worker commands: 'commands.md'
- Further information: 'further_info.md'
 - Troubleshooting: 'trouble.md'
- Changes: 'changes.md'
- To do: 'todo.md'
- Contact information: 'contact.md'
site_dir: html_docs/worker
theme: readthedocs
