#ifndef PROCEESSOR_HDR
#define PROCEESSOR_HDR

#include "result.h"

namespace worker {
    namespace work_processor {
        
        /*!
          \brief executes the argument string as Bash script
          \param work_item std::string representing a Bash script to be
                 executed
          \return result object containing the exit status, the standard
                  output and error generated by executing the Bash scriot.
         */
        Result process_work(const std::string work_item);

    }
}

#endif
